

const fake =[
    {title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.'},
    {title: 'Vero voluptatibus eum,'},
    {title: 'sunt maxime pariatur nulla a? '},
    {title: 'Eligendi placeat officia officiis, '},
    {title: 'delectus sint dignissimos excepturi qui aspernatur '},
    {title: 'quidem, eum corporis laboriosam eveniet perspiciatis '},
    {title: 'iusto tempore ab ex molestias labore earum? '},
    {title: 'Facilis, quisquam aliquam.'},
    {title: 'Nihil optio officiis obcaecati,'},
    {title: 'repudiandae architecto corporis placeat cupiditate  '},
    {title: 'numquam aut suscipit ex earum quas explicabo unde ut voluptatem veritatis hic.'},
    {title: 'Velit eos veniam, voluptatum laborum '},
    {title: ' animi delectus quod cumque pariatur accusantium qui id sunt, '},
    {title: 'itaque facilis, enim dolor temporibus dicta! '},
    {title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.'},
    {title: 'Vero voluptatibus eum,'},
    {title: 'sunt maxime pariatur nulla a? '},
    {title: 'Eligendi placeat officia officiis, '},
    {title: 'delectus sint dignissimos excepturi qui aspernatur '},
    {title: 'quidem, eum corporis laboriosam eveniet perspiciatis '},
    {title: 'iusto tempore ab ex molestias labore earum? '},
    {title: 'Facilis, quisquam aliquam.'},
    {title: 'Nihil optio officiis obcaecati,'},
    {title: 'repudiandae architecto corporis placeat cupiditate  '},
    {title: 'numquam aut suscipit ex earum quas explicabo unde ut voluptatem veritatis hic.'},
    {title: 'Velit eos veniam, voluptatum laborum '},
    {title: ' animi delectus quod cumque pariatur accusantium qui id sunt, '},
    {title: 'itaque facilis, enim dolor temporibus dicta! '},
    {title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.'},
    {title: 'Vero voluptatibus eum,'},
    {title: 'sunt maxime pariatur nulla a? '},
    {title: 'Eligendi placeat officia officiis, '},
    {title: 'delectus sint dignissimos excepturi qui aspernatur '},
    {title: 'quidem, eum corporis laboriosam eveniet perspiciatis '},
    {title: 'iusto tempore ab ex molestias labore earum? '},
    {title: 'Facilis, quisquam aliquam.'},
    {title: 'Nihil optio officiis obcaecati,'},
    {title: 'repudiandae architecto corporis placeat cupiditate  '},
    {title: 'numquam aut suscipit ex earum quas explicabo unde ut voluptatem veritatis hic.'},
    {title: 'Velit eos veniam, voluptatum laborum '},
    {title: ' animi delectus quod cumque pariatur accusantium qui id sunt, '},
    {title: 'itaque facilis, enim dolor temporibus dicta! '},
]

export default fake